theme: jekyll-theme-minimal
title: David Williams' homepage
description: Website for Dr David R A Williams

logo: <img src="/figures/275911576_10158192491852102_7087395702249941919_n copy.png" alt="" class="img-fluid rounded-circle">
