theme: jekyll-theme-minimal
title: David Williams' homepage
description: Website for Dr David R A Williams

![David Williams](https://github.com/DRAWilliams/drawilliams.github.io/figures/188900281_10157702375437102_7982515067396528773_n.jpeg?raw=true)
