theme: jekyll-theme-minimal
title: David Williams' homepage
description: Website for Dr David R A Williams

<a href="https://twitter.com/TheAstroDave" class="twitter"><i class="bx bxl-twitter"></i></a>
